### PR TITLE
ext2fs: patch ext2fs.h for glibc 2.30 compatibility

### PR DESCRIPTION
**Pull request by xginn8**
Change-type: patch
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by zvin** [comment]
What error were you getting?
Why is this added inside `#if !defined(__aarch64__)`?

**Comment by xginn8** [comment]
> What error were you getting?
> Why is this added inside `#if !defined(__aarch64__)`?

Arch Linux users were reporting that etcher builds failed (error below). Upon closer investigation, the error reported occurred when compiling this library. Some logs available here: https://aur.archlinux.org/packages/balena-etcher/#comment-711525. I was able to track this down to glibc upgrading from 2.29 to 2.30, and other projects reported similar errors: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/merge_requests/292. I can't vouch for other architectures, but this patch fixes the issue on Arch Linux x86_64.

```
In file included from ../src/node_ext2fs.cc:5:
../src/ext2fs.h: At global scope:
../src/ext2fs.h:20:18: error: conflicting declaration ‘typedef uint64_t __u64’
   20 | typedef uint64_t __u64;
      |                  ^~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/asm/types.h:5,
                 from /usr/include/linux/types.h:5,
                 from /usr/include/linux/stat.h:5,
                 from /usr/include/bits/statx.h:30,
                 from /usr/include/sys/stat.h:446,
                 from /home/matthew/.cache/node-gyp/iojs-3.1.9/deps/uv/include/uv-unix.h:26,
                 from /home/matthew/.cache/node-gyp/iojs-3.1.9/deps/uv/include/uv.h:62,
                 from ../node_modules/nan/nan.h:52,
                 from ../src/node_ext2fs.cc:2:
/usr/include/asm-generic/int-ll64.h:31:42: note: previous declaration as ‘typedef long long unsigned int __u64’
   31 | __extension__ typedef unsigned long long __u64;
      |      
```

**Comment by zvin** [comment]
This breaks the build for me (Ubuntu 19.04):
```
In file included from ../src/node_ext2fs.cc:5:
../src/ext2fs.h: At global scope:
../src/ext2fs.h:23:18: error: conflicting declaration ‘typedef uint64_t __u64’
 typedef uint64_t __u64;
                  ^~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/x86_64-linux-gnu/asm/types.h:5,
                 from /usr/include/linux/types.h:5,
                 from ../src/ext2fs.h:21,
                 from ../src/node_ext2fs.cc:5:
/usr/include/asm-generic/int-ll64.h:31:42: note: previous declaration as ‘typedef long long unsigned int __u64’
 __extension__ typedef unsigned long long __u64;
```

**Comment by xginn8** [comment]
@zvin thanks for the feedback, I will try to clean this up.

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by zvin** [comment]
Looks good now.
I'd like to check if it still builds on arm64 before merging.

**Comment by xginn8** [comment]
I've confirmed rebuilding this on an RPi3 armv7l, fwiw. Once you're comfortable with it, I will merge.

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by zvin** [comment]
Just checked, it builds on aarch64 \o/

**Pull request merged**
